defmodule SlackOpenApi.Web.ObjsUserProfile do
  @moduledoc """
  Provides struct and type for a ObjsUserProfile
  """

  @type t :: %__MODULE__{
          always_active: boolean | nil,
          api_app_id: String.t() | nil,
          avatar_hash: String.t(),
          bot_id: String.t() | nil,
          display_name: String.t(),
          display_name_normalized: String.t(),
          email: String.t() | nil,
          fields: map | [map] | nil,
          first_name: String.t() | nil,
          guest_expiration_ts: integer | nil,
          guest_invited_by: String.t() | nil,
          image_1024: String.t() | nil,
          image_192: String.t() | nil,
          image_24: String.t() | nil,
          image_32: String.t() | nil,
          image_48: String.t() | nil,
          image_512: String.t() | nil,
          image_72: String.t() | nil,
          image_original: String.t() | nil,
          is_app_user: boolean | nil,
          is_custom_image: boolean | nil,
          is_restricted: boolean | nil,
          is_ultra_restricted: boolean | nil,
          last_avatar_image_hash: String.t() | nil,
          last_name: String.t() | nil,
          memberships_count: integer | nil,
          name: String.t() | nil,
          phone: String.t(),
          pronouns: String.t() | nil,
          real_name: String.t(),
          real_name_normalized: String.t(),
          skype: String.t(),
          status_default_emoji: String.t() | nil,
          status_default_text: String.t() | nil,
          status_default_text_canonical: String.t() | nil,
          status_emoji: String.t(),
          status_expiration: integer | nil,
          status_text: String.t(),
          status_text_canonical: String.t() | nil,
          team: String.t() | nil,
          title: String.t(),
          updated: integer | nil,
          user_id: String.t() | nil,
          username: String.t() | nil
        }

  defstruct [
    :always_active,
    :api_app_id,
    :avatar_hash,
    :bot_id,
    :display_name,
    :display_name_normalized,
    :email,
    :fields,
    :first_name,
    :guest_expiration_ts,
    :guest_invited_by,
    :image_1024,
    :image_192,
    :image_24,
    :image_32,
    :image_48,
    :image_512,
    :image_72,
    :image_original,
    :is_app_user,
    :is_custom_image,
    :is_restricted,
    :is_ultra_restricted,
    :last_avatar_image_hash,
    :last_name,
    :memberships_count,
    :name,
    :phone,
    :pronouns,
    :real_name,
    :real_name_normalized,
    :skype,
    :status_default_emoji,
    :status_default_text,
    :status_default_text_canonical,
    :status_emoji,
    :status_expiration,
    :status_text,
    :status_text_canonical,
    :team,
    :title,
    :updated,
    :user_id,
    :username
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      always_active: :boolean,
      api_app_id: {:string, :generic},
      avatar_hash: {:string, :generic},
      bot_id: {:string, :generic},
      display_name: {:string, :generic},
      display_name_normalized: {:string, :generic},
      email: {:string, :email},
      fields: {:union, [:map, [:map]]},
      first_name: {:string, :generic},
      guest_expiration_ts: :integer,
      guest_invited_by: {:string, :generic},
      image_1024: {:string, :uri},
      image_192: {:string, :uri},
      image_24: {:string, :uri},
      image_32: {:string, :uri},
      image_48: {:string, :uri},
      image_512: {:string, :uri},
      image_72: {:string, :uri},
      image_original: {:string, :uri},
      is_app_user: :boolean,
      is_custom_image: :boolean,
      is_restricted: :boolean,
      is_ultra_restricted: :boolean,
      last_avatar_image_hash: {:string, :generic},
      last_name: {:string, :generic},
      memberships_count: :integer,
      name: {:string, :generic},
      phone: {:string, :generic},
      pronouns: {:string, :generic},
      real_name: {:string, :generic},
      real_name_normalized: {:string, :generic},
      skype: {:string, :generic},
      status_default_emoji: {:string, :generic},
      status_default_text: {:string, :generic},
      status_default_text_canonical: {:string, :generic},
      status_emoji: {:string, :generic},
      status_expiration: :integer,
      status_text: {:string, :generic},
      status_text_canonical: {:string, :generic},
      team: {:string, :generic},
      title: {:string, :generic},
      updated: :integer,
      user_id: {:string, :generic},
      username: {:string, :generic}
    ]
  end
end
