defmodule SlackOpenApi.Web.ObjsFile do
  @moduledoc """
  Provides struct and type for a ObjsFile
  """

  @type t :: %__MODULE__{
          channels: [String.t()] | nil,
          comments_count: integer | nil,
          created: integer | nil,
          date_delete: integer | nil,
          display_as_bot: boolean | nil,
          editable: boolean | nil,
          editor: String.t() | nil,
          external_id: String.t() | nil,
          external_type: String.t() | nil,
          external_url: String.t() | nil,
          filetype: String.t() | nil,
          groups: [String.t()] | nil,
          has_rich_preview: boolean | nil,
          id: String.t() | nil,
          image_exif_rotation: integer | nil,
          ims: [String.t()] | nil,
          is_external: boolean | nil,
          is_public: boolean | nil,
          is_starred: boolean | nil,
          is_tombstoned: boolean | nil,
          last_editor: String.t() | nil,
          mimetype: String.t() | nil,
          mode: String.t() | nil,
          name: String.t() | nil,
          non_owner_editable: boolean | nil,
          num_stars: integer | nil,
          original_h: integer | nil,
          original_w: integer | nil,
          permalink: String.t() | nil,
          permalink_public: String.t() | nil,
          pinned_info: SlackOpenApi.Web.DefsPinnedInfo.t() | nil,
          pinned_to: [String.t()] | nil,
          pretty_type: String.t() | nil,
          preview: String.t() | nil,
          public_url_shared: boolean | nil,
          reactions: [SlackOpenApi.Web.ObjsReaction.t()] | nil,
          shares: SlackOpenApi.Web.ObjsFileShares.t() | nil,
          size: integer | nil,
          source_team: String.t() | nil,
          state: String.t() | nil,
          thumb_1024: String.t() | nil,
          thumb_1024_h: integer | nil,
          thumb_1024_w: integer | nil,
          thumb_160: String.t() | nil,
          thumb_360: String.t() | nil,
          thumb_360_h: integer | nil,
          thumb_360_w: integer | nil,
          thumb_480: String.t() | nil,
          thumb_480_h: integer | nil,
          thumb_480_w: integer | nil,
          thumb_64: String.t() | nil,
          thumb_720: String.t() | nil,
          thumb_720_h: integer | nil,
          thumb_720_w: integer | nil,
          thumb_80: String.t() | nil,
          thumb_800: String.t() | nil,
          thumb_800_h: integer | nil,
          thumb_800_w: integer | nil,
          thumb_960: String.t() | nil,
          thumb_960_h: integer | nil,
          thumb_960_w: integer | nil,
          thumb_tiny: String.t() | nil,
          timestamp: integer | nil,
          title: String.t() | nil,
          updated: integer | nil,
          url_private: String.t() | nil,
          url_private_download: String.t() | nil,
          user: String.t() | nil,
          user_team: String.t() | nil,
          username: String.t() | nil
        }

  defstruct [
    :channels,
    :comments_count,
    :created,
    :date_delete,
    :display_as_bot,
    :editable,
    :editor,
    :external_id,
    :external_type,
    :external_url,
    :filetype,
    :groups,
    :has_rich_preview,
    :id,
    :image_exif_rotation,
    :ims,
    :is_external,
    :is_public,
    :is_starred,
    :is_tombstoned,
    :last_editor,
    :mimetype,
    :mode,
    :name,
    :non_owner_editable,
    :num_stars,
    :original_h,
    :original_w,
    :permalink,
    :permalink_public,
    :pinned_info,
    :pinned_to,
    :pretty_type,
    :preview,
    :public_url_shared,
    :reactions,
    :shares,
    :size,
    :source_team,
    :state,
    :thumb_1024,
    :thumb_1024_h,
    :thumb_1024_w,
    :thumb_160,
    :thumb_360,
    :thumb_360_h,
    :thumb_360_w,
    :thumb_480,
    :thumb_480_h,
    :thumb_480_w,
    :thumb_64,
    :thumb_720,
    :thumb_720_h,
    :thumb_720_w,
    :thumb_80,
    :thumb_800,
    :thumb_800_h,
    :thumb_800_w,
    :thumb_960,
    :thumb_960_h,
    :thumb_960_w,
    :thumb_tiny,
    :timestamp,
    :title,
    :updated,
    :url_private,
    :url_private_download,
    :user,
    :user_team,
    :username
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      channels: [string: :generic],
      comments_count: :integer,
      created: :integer,
      date_delete: :integer,
      display_as_bot: :boolean,
      editable: :boolean,
      editor: {:string, :generic},
      external_id: {:string, :generic},
      external_type: {:string, :generic},
      external_url: {:string, :uri},
      filetype: {:string, :generic},
      groups: [string: :generic],
      has_rich_preview: :boolean,
      id: {:string, :generic},
      image_exif_rotation: :integer,
      ims: [string: :generic],
      is_external: :boolean,
      is_public: :boolean,
      is_starred: :boolean,
      is_tombstoned: :boolean,
      last_editor: {:string, :generic},
      mimetype: {:string, :generic},
      mode: {:string, :generic},
      name: {:string, :generic},
      non_owner_editable: :boolean,
      num_stars: :integer,
      original_h: :integer,
      original_w: :integer,
      permalink: {:string, :uri},
      permalink_public: {:string, :uri},
      pinned_info: {SlackOpenApi.Web.DefsPinnedInfo, :t},
      pinned_to: [string: :generic],
      pretty_type: {:string, :generic},
      preview: {:string, :generic},
      public_url_shared: :boolean,
      reactions: [{SlackOpenApi.Web.ObjsReaction, :t}],
      shares: {SlackOpenApi.Web.ObjsFileShares, :t},
      size: :integer,
      source_team: {:string, :generic},
      state: {:string, :generic},
      thumb_1024: {:string, :uri},
      thumb_1024_h: :integer,
      thumb_1024_w: :integer,
      thumb_160: {:string, :uri},
      thumb_360: {:string, :uri},
      thumb_360_h: :integer,
      thumb_360_w: :integer,
      thumb_480: {:string, :uri},
      thumb_480_h: :integer,
      thumb_480_w: :integer,
      thumb_64: {:string, :uri},
      thumb_720: {:string, :uri},
      thumb_720_h: :integer,
      thumb_720_w: :integer,
      thumb_80: {:string, :uri},
      thumb_800: {:string, :uri},
      thumb_800_h: :integer,
      thumb_800_w: :integer,
      thumb_960: {:string, :uri},
      thumb_960_h: :integer,
      thumb_960_w: :integer,
      thumb_tiny: {:string, :generic},
      timestamp: :integer,
      title: {:string, :generic},
      updated: :integer,
      url_private: {:string, :uri},
      url_private_download: {:string, :uri},
      user: {:string, :generic},
      user_team: {:string, :generic},
      username: {:string, :generic}
    ]
  end
end
