defmodule SlackOpenApi.Web.Team do
  @moduledoc """
  Provides API endpoints related to team
  """

  @default_client SlackOpenApi.Client

  @type access_logs_200_json_resp :: %{
          logins: [SlackOpenApi.Web.TeamLogins.access_logs_200_json_resp()],
          ok: true,
          paging: SlackOpenApi.Web.ObjsPaging.t()
        }

  @type access_logs_default_json_resp :: %{
          callstack: String.t() | nil,
          error: String.t(),
          ok: false
        }

  @doc """
  get `/team.accessLogs`

  Gets the access logs for the current team.

  ## Options

    * `token`: Authentication token. Requires scope: `admin`
    * `before`: End of time range of logs to include in results (inclusive).
    * `count`
    * `page`

  ## Resources

    * [API method documentation](https://api.slack.com/methods/team.accessLogs)

  """
  @spec access_logs(keyword) :: {:ok, map} | {:error, map}
  def access_logs(opts \\ []) do
    client = opts[:client] || @default_client
    query = Keyword.take(opts, [:before, :count, :page, :token])

    client.request(%{
      args: [],
      call: {SlackOpenApi.Web.Team, :access_logs},
      url: "/team.accessLogs",
      method: :get,
      query: query,
      response: [
        {200, {SlackOpenApi.Web.Team, :access_logs_200_json_resp}},
        default: {SlackOpenApi.Web.Team, :access_logs_default_json_resp}
      ],
      opts: opts
    })
  end

  @type billable_info_200_json_resp :: %{ok: true}

  @type billable_info_default_json_resp :: %{ok: false}

  @doc """
  get `/team.billableInfo`

  Gets billable users information for the current team.

  ## Options

    * `token`: Authentication token. Requires scope: `admin`
    * `user`: A user to retrieve the billable information for. Defaults to all users.

  ## Resources

    * [API method documentation](https://api.slack.com/methods/team.billableInfo)

  """
  @spec billable_info(keyword) :: {:ok, map} | {:error, map}
  def billable_info(opts \\ []) do
    client = opts[:client] || @default_client
    query = Keyword.take(opts, [:token, :user])

    client.request(%{
      args: [],
      call: {SlackOpenApi.Web.Team, :billable_info},
      url: "/team.billableInfo",
      method: :get,
      query: query,
      response: [
        {200, {SlackOpenApi.Web.Team, :billable_info_200_json_resp}},
        default: {SlackOpenApi.Web.Team, :billable_info_default_json_resp}
      ],
      opts: opts
    })
  end

  @type info_200_json_resp :: %{ok: true, team: SlackOpenApi.Web.ObjsTeam.t()}

  @type info_default_json_resp :: %{callstack: String.t() | nil, error: String.t(), ok: false}

  @doc """
  get `/team.info`

  Gets information about the current team.

  ## Options

    * `token`: Authentication token. Requires scope: `team:read`
    * `team`: Team to get info on, if omitted, will return information about the current team. Team to get info about; if omitted, will return information about the current team.

  ## Resources

    * [API method documentation](https://api.slack.com/methods/team.info)

  """
  @spec info(keyword) :: {:ok, map} | {:error, map}
  def info(opts \\ []) do
    client = opts[:client] || @default_client
    query = Keyword.take(opts, [:team, :token])

    client.request(%{
      args: [],
      call: {SlackOpenApi.Web.Team, :info},
      url: "/team.info",
      method: :get,
      query: query,
      response: [
        {200, {SlackOpenApi.Web.Team, :info_200_json_resp}},
        default: {SlackOpenApi.Web.Team, :info_default_json_resp}
      ],
      opts: opts
    })
  end

  @type integration_logs_200_json_resp :: %{
          logs: [SlackOpenApi.Web.TeamLogs.integration_logs_200_json_resp()],
          ok: true,
          paging: SlackOpenApi.Web.ObjsPaging.t()
        }

  @type integration_logs_default_json_resp :: %{
          callstack: String.t() | nil,
          error: String.t(),
          ok: false
        }

  @doc """
  get `/team.integrationLogs`

  Gets the integration logs for the current team.

  ## Options

    * `token`: Authentication token. Requires scope: `admin`
    * `app_id`: Filter logs to this Slack app. Defaults to all logs.
    * `change_type`: Filter logs with this change type. Defaults to all logs.
    * `count`
    * `page`
    * `service_id`: Filter logs to this service. Defaults to all logs.
    * `user`: Filter logs generated by this user’s actions. Defaults to all logs.

  ## Resources

    * [API method documentation](https://api.slack.com/methods/team.integrationLogs)

  """
  @spec integration_logs(keyword) :: {:ok, map} | {:error, map}
  def integration_logs(opts \\ []) do
    client = opts[:client] || @default_client
    query = Keyword.take(opts, [:app_id, :change_type, :count, :page, :service_id, :token, :user])

    client.request(%{
      args: [],
      call: {SlackOpenApi.Web.Team, :integration_logs},
      url: "/team.integrationLogs",
      method: :get,
      query: query,
      response: [
        {200, {SlackOpenApi.Web.Team, :integration_logs_200_json_resp}},
        default: {SlackOpenApi.Web.Team, :integration_logs_default_json_resp}
      ],
      opts: opts
    })
  end

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(:access_logs_200_json_resp) do
    [
      logins: [{SlackOpenApi.Web.TeamLogins, :access_logs_200_json_resp}],
      ok: {:const, true},
      paging: {SlackOpenApi.Web.ObjsPaging, :t}
    ]
  end

  def __fields__(:access_logs_default_json_resp) do
    [
      callstack: {:string, :generic},
      error:
        {:enum,
         [
           "paid_only",
           "over_pagination_limit",
           "not_authed",
           "invalid_auth",
           "account_inactive",
           "token_revoked",
           "no_permission",
           "org_login_required",
           "user_is_bot",
           "invalid_arg_name",
           "invalid_array_arg",
           "invalid_charset",
           "invalid_form_data",
           "invalid_post_type",
           "missing_post_type",
           "team_added_to_org",
           "invalid_json",
           "json_not_object",
           "request_timeout",
           "upgrade_required",
           "fatal_error"
         ]},
      ok: {:const, false}
    ]
  end

  def __fields__(:billable_info_200_json_resp) do
    [ok: {:const, true}]
  end

  def __fields__(:billable_info_default_json_resp) do
    [ok: {:const, false}]
  end

  def __fields__(:info_200_json_resp) do
    [ok: {:const, true}, team: {SlackOpenApi.Web.ObjsTeam, :t}]
  end

  def __fields__(:info_default_json_resp) do
    [
      callstack: {:string, :generic},
      error:
        {:enum,
         [
           "not_authed",
           "invalid_auth",
           "account_inactive",
           "token_revoked",
           "no_permission",
           "invalid_arg_name",
           "invalid_array_arg",
           "invalid_charset",
           "invalid_form_data",
           "invalid_post_type",
           "missing_post_type",
           "team_added_to_org",
           "invalid_json",
           "json_not_object",
           "request_timeout",
           "upgrade_required",
           "fatal_error"
         ]},
      ok: {:const, false}
    ]
  end

  def __fields__(:integration_logs_200_json_resp) do
    [
      logs: [{SlackOpenApi.Web.TeamLogs, :integration_logs_200_json_resp}],
      ok: {:const, true},
      paging: {SlackOpenApi.Web.ObjsPaging, :t}
    ]
  end

  def __fields__(:integration_logs_default_json_resp) do
    [
      callstack: {:string, :generic},
      error:
        {:enum,
         [
           "not_authed",
           "invalid_auth",
           "account_inactive",
           "token_revoked",
           "no_permission",
           "org_login_required",
           "user_is_bot",
           "invalid_arg_name",
           "invalid_array_arg",
           "invalid_charset",
           "invalid_form_data",
           "invalid_post_type",
           "missing_post_type",
           "team_added_to_org",
           "invalid_json",
           "json_not_object",
           "request_timeout",
           "upgrade_required",
           "fatal_error"
         ]},
      ok: {:const, false}
    ]
  end
end
